### ISSUE TITLE
tiled version

### ISSUE THREAD

**Issue by fnaith** [Yanrishatum/haxe-format-tiled#2]
Exciting to see a tiled support haxe library updated in 2018 :)

But, does it support recentr tiled veriosn(1.1) ?

**Comment by Yanrishatum** [comment]
Almost none of the new features. Frankly I wanted to wait for 1.2 to release as there are features I await the most. But if you want to specify some unsupported features I may add them before 1.2 release.

**Comment by fnaith** [comment]
Not really needs new feature. But new tmx file has ' tiledversion="1.1.0" ' meta data in xml header.

I just wonder it is compatible format for this library or not.

I guess it is.

**Comment by Yanrishatum** [comment]
It is compatible with newer versions, just don't support a lot of new features (like infinite maps or property types).

**Comment by fnaith** [comment]
Awesome!
