### ISSUE TITLE
Compile fail with cs (and probably java)

### ISSUE THREAD

**Issue by fnaith** [Yanrishatum/haxe-format-tiled#4]
When I compile Data.hx, the error "No suitable overload for the super call arguments was found" happened on TmxImageLayer, TmxTileLayer and TmxObjectGroup class.

I guess this [commit](https://groups.google.com/forum/#!topic/haxedev/R9kUqiRYQ44) for [java/cs] isn't compatible with @structInit.

I hotfix by adding constructor and assign members manually as following:

```
@:structInit
class TmxImageLayer extends TmxBaseLayer
{
	@:optional public var image:TmxImage;

	public function new() {
		super();
	}
}

private function resolveImageLayer(input:Fast):TmxImageLayer
{
	var layer:TmxImageLayer = new TmxImageLayer();
	layer.name = input.att.name;
	layer.x = input.has.x ? Std.parseFloat(input.att.x) : 0;
	layer.y = input.has.y ? Std.parseFloat(input.att.y) : 0;
	layer.offsetX = input.has.offsetx ? Std.parseInt(input.att.offsetx) : 0;
	layer.offsetY = input.has.offsety ? Std.parseInt(input.att.offsety) : 0;
	layer.width = input.has.width ? Std.parseInt(input.att.width) : width;
	layer.height = input.has.height ? Std.parseInt(input.att.height) : height;
	layer.opacity = input.has.opacity ? Std.parseFloat(input.att.opacity) : 1;
	layer.visible = input.has.visible ? input.att.visible == "1" : true;
	layer.properties = resolveProperties(input);
	layer.image = input.hasNode.image ? resolveImage(input.node.image) : null;
	return layer;
}

// repeat 3 times for each class, fortunately each constructor is used only 1 times ...
```

However, it may lose meaning about adding @:structInit.

Maybe there is some more elegant solution for this problem?
If not, I could close this issue and living with hotfix :)

**Comment by Yanrishatum** [comment]
If you aren't afraid of performance punch which `typedefs` would bring, you can replace almost all `@:structInit class` to `typedef` (and the `>BaseClass,` inheritance method). I decided to go with classes for better performance, but typedefs is still a solution. 

I never tested library with anything other than JS, CPP, HashLink and Neko. But given `@:structInit` is in the Haxe core, it's a bug in Java/C# part and I'd suggest making an issue on their side. :)

**Comment by fnaith** [comment]
sure ! Many thanks~~~
