### ISSUE TITLE
gid in TmxTile should be long

### ISSUE THREAD

**Issue by fnaith** [Yanrishatum/haxe-format-tiled#5]
Will ... when flippedVertically of TmxTile is true, the gid will bigger than int max  (2147483697).

In that case gid will be loaded as negative number and crash data.

**Comment by fnaith** [comment]
looks like use unsigned int is fine.

**Comment by Yanrishatum** [comment]
What target are you using? I'm aware of the issue and there are workarounds in place for few (neko/cpp) targets. GIDs are unsigned ints, but haxe STD library does not provide method of parsing uint from string.

**Comment by fnaith** [comment]
mmm..  understand, thaks a lot!
